######################
# Translation
######################

# Stifness Matrices
# ==================
# reach
Kp_0: [ -10., 0.0, 0.0, 0.0, -10., 0.0, 0.0, 0.0, -10.]
# toss
Kp_1: [  -10., 0.0, 0.0, 0.0, -10., 0.0, 0.0, 0.0, -10.]
# retract
Kp_2: [  -10., 0.0, 0.0, 0.0, -10., 0.0, 0.0, 0.0, -10.]

# Damping Matrices
# ==================
# reach
Dp_0: [  -6.32, 0.0, 0.0, 0.0, -6.32, 0.0, 0.0, 0.0, -6.32]
# toss
Dp_1: [  -6.32, 0.0, 0.0, 0.0, -6.32, 0.0, 0.0, 0.0, -6.32]
# retract
Dp_2: [  -6.32, 0.0, 0.0,  0.0, -6.32, 0.0, 0.0, 0.0, -6.32]

# Stifness Matrices
# ==================
 # reach
Ko_0: [  -3., 0.0, 0.0, 0.0, -3., 0.0, 0.0, 0.0, -3.]
# toss
Ko_1: [  -3., 0.0, 0.0, 0.0, -3., 0.0, 0.0, 0.0, -3.]
# retract
Ko_2: [  -3., 0.0, 0.0, 0.0, -3., 0.0, 0.0, 0.0, -3.]

# Damping Matrices
# ==================
 # reach
Do_0: [  -3.46, 0.0, 0.0, 0.0, -3.46, 0.0, 0.0, 0.0, -3.46]
# toss
Do_1: [  -3.46, 0.0, 0.0, 0.0, -3.46, 0.0, 0.0, 0.0, -3.46]
 # retract
Do_2: [  -3.46, 0.0, 0.0, 0.0, -3.46, 0.0, 0.0, 0.0, -3.46]